# Generated by Django 6.0.2 on 2026-03-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='due_date',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='submitted_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='grade',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(upload_to='assignmets/'),
        ),
    ]
