# Generated by Django 6.0.2 on 2026-03-04 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizattempt_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='student',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
